# Copy to config/kestra/secrets.yml and provide service credentials.
kestra:
  datasources:
    main:
      username: kestra
      password: kestra
  foundationdb:
    cluster_file: ./config/foundationdb/fdb.cluster

